# Generated by Django 2.1.5 on 2019-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='')),
                ('description', models.CharField(default='SOME STRING', max_length=300)),
            ],
        ),
    ]
